import "../src/styles/dist/css/index.css";

// import ReactPlayer from 'react-player'
import Navbar from "./comps/landing_page/Navbar";
import Hero from "./comps/landing_page/Hero";
import Head from "./comps/landing_page/Head";
import NowShowing from "./comps/landing_page/now_showing";
import Ckd from "./comps/CKD/ckd_page";
import PageBreak from "./comps/CKD/LineBreak";
import { Route, Router, Routes, BrowserRouter } from "react-router-dom";
import MyForm from "./comps/CKD/forms";
import Doc from "./comps/CKD/doc";


export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Layout />} />
        <Route path="ckd" element={<MyForm />}></Route>
        <Route path="doc" element={<Doc/>}></Route>
      </Routes>
    </BrowserRouter>
  );
}

const Topic = () => {
  return (
    <div>
      <h4>title</h4>
      <h5>Author</h5>
    </div>
  );
};

const Layout =() =>{
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        {/* <ReactPlayer url="https://d2vptq57joh8d5.cloudfront.net/y2mate.com%20-%20SARO%20VS%20FEMI%20MECHO%20%20TAAOOMA%20%20KUNLE%20REMI_v240P.mp4" controls={true}></ReactPlayer>  */}
        <Hero />
      </main>
      <PageBreak />
      <Ckd />
      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="logo">
            {/* <Image src="../public/" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  );
}


